spring:
  application:
    name: calinify

  datasource:
    url: jdbc:mysql://localhost:3306/calinify?serverTimezone=UTC
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  firebase:
    config:
      path: "src/main/resources/firebase.json"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


springdoc:

  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html